Added what seems to be a working MD5 image search on archived.moe
Floens/Clover pull request #323
Opened 2017-06-20 01:28 UTC by xela722

My first git contribution so I'm not sure if I did it correctly. Anyway, love your app and really wanted this feature so I tried to put it together myself. Might as well share it.

2017-07-15 11:14 UTC, Floens commented
I can't merge this yet. You're hardcoding some logic on the id `6` and some other stuff. It's best to abstract that away so you can get an url to open from the ImageSearch class itself.

2018-02-07 19:21 UTC, xela722 commented
I tried this again on the dev version. I think it's better this time, but check to make sure.

2018-02-07 20:08 UTC, floens requested changes
I've reviewed the code.
It's good, but there are a few small things that need changing.
Did you test this? It seems that the makeArgument with 3 pairs is not used.

Also, please remove the unnecessary gradle files.

2018-02-07 20:08 UTC, Floens commented on Clover/app/src/main/java/org/floens/chan/core/site/ImageSearch.java
> +    public abstract String getType();
Make this an enum or a static final int.
You can put the enum on the ImageSearch class.

2018-02-07 20:08 UTC, Floens commented on Clover/app/src/main/java/org/floens/chan/core/site/ImageSearch.java
> +                return "MD5";
Should be the name of the search engine.

2018-02-07 20:08 UTC, Floens commented on Clover/app/src/main/java/org/floens/chan/core/site/SiteEndpoints.java
> +        Map<String, String> map = new ArrayMap<>(2);
Change `2` to `3`. It's there to reserve a space to the arraymap.

2018-02-07 20:08 UTC, Floens commented on Clover/app/src/main/java/org/floens/chan/core/site/SiteEndpoints.java
> +        map.put(key2, value2);
Also add key3/value3

2018-02-07 20:08 UTC, Floens commented on Clover/app/src/main/java/org/floens/chan/ui/controller/ImageViewerController.java
> +                                if(imageSearch.getType()=="link") {
You can't compare strings using `==`. But this will become an enum or const int anyway.

2018-02-07 20:08 UTC, Floens commented on Clover/app/src/main/java/org/floens/chan/ui/controller/ImageViewerController.java
> +        return postImage.type == PostImage.Type.MOVIE ? postImage.md5 : postImage.md5;
This method is redundant, because it always returns `.md5`.

2020-08-30 14:13 UTC, closed without merging